# Generated by Django 3.0.4 on 2020-03-04 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet', models.CharField(choices=[('Mandiri', 'Mandiri'), ('BCA', 'BCA'), ('BRI', 'BRI'), ('Cash', 'Cash')], max_length=20)),
                ('total', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=100)),
                ('total', models.IntegerField()),
                ('destination', models.CharField(choices=[('Mandiri', 'Mandiri'), ('BCA', 'BCA'), ('BRI', 'BRI'), ('Cash', 'Cash')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Debit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('Mandiri', 'Mandiri'), ('BCA', 'BCA'), ('BRI', 'BRI'), ('Cash', 'Cash')], max_length=20)),
                ('total', models.IntegerField()),
                ('description', models.CharField(max_length=255)),
                ('type_outcome', models.CharField(choices=[('Donation', 'Donation'), ('Daily', 'Daily'), ('Holiday', 'Holiday')], max_length=100)),
            ],
        ),
    ]
