# Generated by Django 3.0.4 on 2020-03-04 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='debit',
            old_name='type_outcome',
            new_name='type_spending',
        ),
    ]
