# Generated by Django 3.0.4 on 2020-03-06 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_auto_20200304_1242'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('Credit', 'Credit'), ('Debit', 'Debit')], max_length=20)),
                ('wallet', models.CharField(choices=[('Mandiri', 'Mandiri'), ('BCA', 'BCA'), ('BRI', 'BRI'), ('Cash', 'Cash')], max_length=20)),
                ('total', models.IntegerField()),
                ('description', models.CharField(max_length=255)),
                ('spending', models.CharField(blank=True, choices=[('Donation', 'Donation'), ('Daily', 'Daily'), ('Holiday', 'Holiday')], max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Credit',
        ),
        migrations.DeleteModel(
            name='Debit',
        ),
    ]
