# Generated by Django 3.0.4 on 2020-03-07 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_auto_20200306_0606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
